# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 08 Dec 2017 05:59:13 +0000
*               @ALL          1
*               @user         8
